### PR TITLE
Rcppification

### PR DESCRIPTION
**Pull request by maelle**
Converting core financial functions to Rcpp for performance improvement

### CODE REVIEW

**Comment by maelle** [comment]
@ritagior could you (or should I?)

* Update DESCRIPTION? I'd recommend doing the setup of `whoami` and then use `desc::desc_add_me`

* Update NEWS?

* Add the vignette you created to the `pkgdown` website?

**Comment by maelle** [comment]
Mmmh what I said about the benchmark doesn't make much sense, but it'd be great to add how big the speedup was, and to move the benchmark of the old and new functions to an inst/benchmark folder that'd be .Rbuildignored?

**Comment by stephlocke** [comment]
Rcpp requirement should be explicit in DESCRIPTION?

**Comment by stephlocke** [comment]
Could the names of the cpp functions and files be consistent, either all [fn]cpp or all [fn]_cpp

**Comment by ritagior** [comment]
DESCRIPTION is update with Rcpp requirement and I pushed the new version.

**Comment by stephlocke** [comment]
CI failed - looks like it's because both instances of functions being exported at the mo
> /tmp/RtmprzRGk5/Rbuild5bcc7cdb6f54/optiRum/src/ratecpp.cpp:12: multiple definition of `ratecpp(Rcpp::Vector<14, Rcpp::PreserveStorage>, Rcpp::Vector<14, Rcpp::PreserveStorage>, Rcpp::Vector<14, Rcpp::PreserveStorage>)'

**Comment by ritagior** [comment]
removed ratecpp.cpp

**Comment by stephlocke** [comment]
Woohoo! Tests Passing 👏

**Pull request closed without merging**
